### ISSUE TITLE
Local state precedence in class variable annotations

### ISSUE THREAD

**Issue by ambv** [ambv/static-annotations#1]
Q: Would you rather maintain the current situation that local names in class annotations take precedence over module-level names?

If so, that means class annotations could no longer use global types in case of a conflict.  On the one hand I understand this is in line with what Python's scoping does.  On the other hand, absolute imports are a counter-example.  Since we cannot use the "global" keyword in type annotations (nor in imports), I think defaulting to "absolute" makes sense.

## Context ##

I already fixed get_type_hints() to find globalns correctly by default: https://github.com/python/typing/commit/468b3fe965fac7b11c0c306fff19c6d56b169b7a

This way you can address internal state of the class by using fully-qualified names.  This is important in case of name conflicts.  Relevant example from the commit below.  Note: this is using variable annotations with the current (pre-PEP 563) behavior.

```py
    class A(Generic[T]):
        some_b: 'B'

    class B(Generic[T]):
        class A(Generic[T]):
            pass

        my_inner_a1: 'B.A'  
        my_inner_a2: A
        my_outer_a: 'A'  # unless somebody calls get_type_hints with localns=B.__dict__
```

So, note that for forward definitions the current default behavior is already "absolute" scoping (module-level names take precedence).

Post-PEP 563 the behavior would be this:
```py
   class B(Generic[T]):
        class A: ...

        my_inner_a: B.A  
        my_outer_a: A  # unless somebody calls get_type_hints with localns=B.__dict__

```

I think this is cleaner, lets users address both "A" unambiguously. I acknowledge it requires users to adopt to it though but at least it's a way out. Leaving local state precedence won't let people address global types at all AFAICT.

**Comment by gvanrossum** [comment]
I ran the example through mypy and found a trivial error: the inner class A can't reuse the type variable T because it's already bound by the containing B -- solution is to use a different type variable, or better to not make it generic (generics don't add anything to the example anyway).

With that fixed, mypy takes all unqualified references inside B to refer to B.A, regardless of quoting. So it is exactly backwards from your version. The mypy behavior (which I prefer) is:
```py
class A: ...
A_alias = A
class B:
    class A: ...
    my_inner_a: A  
    my_outer_a: A_alias  # There's no way to reference outer A without such an alias
```

**Comment by ambv** [comment]
Alright, if this is your preference then I'll implement it in the PEP and make `get_type_hints()` behave like it, too.

**Comment by ambv** [comment]
(the Generic part comes from the fact those types are re-used by a bunch of unit tests in typing; but yes, they are irrelevant for this discussion)

**Comment by ambv** [comment]
Solved in https://github.com/ambv/static-annotations/commit/7bdfa33a2a14011bea1bba6146438741e1e9bb57. Leaving open pending discussion.
