### ISSUE TITLE
First example in "Backwards Compatibility" is distracting

### ISSUE THREAD

**Issue by gvanrossum** [ambv/static-annotations#2]
The example demonstrates how scopes (don't) work using something that's not a type:
```py
def generate_class():
    some_local = datetime.datetime.now()
    class C:
        field: some_local = 1  # NOTE: INVALID ANNOTATION
        def method(self, arg: some_local.day) -> None:  # NOTE: INVALID ANNOTATION
            ...
```
Maybe it's intentional (to point out that the backwards compatibility mostly affects non-type annotations) but I think this is secondary to a similar example using valid types, e.g.
```py
def generate():
    A = Optional[int]
    class C:
        field: A = 1
        def method(self, arg: A) -> None: ...
    return C
X = generate()
print(X.__annotations__)
print(X.method.__annotations__)
```
The question is, does that also become invalid? Mypy has no problem with it. It currently prints
```
{'field': typing.Union[int, NoneType]}
print(C().method.__annotations__)
```
I would expect this to change to
```
{'field': 'A'}
{'arg': 'A', 'return': None}
```
and I would be okay that there would be no way to recover the definition of 'A' given that its scope is gone forever. I would call this backwards incompatible, but I would *not* call it "invalid". A mypy user should be able to write this.

**Comment by ambv** [comment]
Your example hides what is invalid about using local state. You can trivially fix your example by moving the alias out of the function, which is better for performance and enables `get_type_hints()` recover the type.

The thing I wanted to demonstrate is more akin to this (to base on your example):
```
def generate2(type: Type):
    A = Optional[type]
    class C:
        field: A = 1
        def method(self, arg: A) -> None: ...
    return C
X = generate2(int)
print(X.__annotations__)
``` 

mypy is not happy about *that* at all even though `__annotations__` of both `generate()` and `generate2()` is the same at runtime.

**Comment by gvanrossum** [comment]
Hm, I thought the example was intended to highlight what things break, not to pass judgment -- after all in is in the section on backwards incompatibility. You claim that my version can trivially be fixed -- but it's not so trivial if this happens to be a project's prevailing style. Some people are very much into limiting visibility of things, and sometimes this kind of thing happens in test functions where performance doesn't matter but each test has its own set of type definitions. (Tests are a major source of classes defined inside functions in some codebases.)

I present an example that previously worked (i.e. introspection worked) but breaks. You substitute an example that previously doesn't work. I don't see that as an improvement.

**Comment by ambv** [comment]
Alright, I agree. Fixed by https://github.com/ambv/static-annotations/commit/2cd4f599e3d04d23d5e7912150730f05d87d50bf

**Comment by gvanrossum** [comment]
Great!
