### ISSUE TITLE
Deprecation schedule

### ISSUE THREAD

**Issue by gvanrossum** [ambv/static-annotations#3]
The PEP currently proposes to raise `PendingDeprecationWarning` in Python 3.7 when type annotations are used without this `__future__` import. That seems a little harsh (even though the warning is silent by default). I'm not even sure that any of the Python 3 series should consider this truly deprecated -- we could say it'll become the default (and only) behavior in 4.0, and we could start warning about the pending deprecation in 3.8. That seems soon enough, and won't stop anyone from aggressively adopting this. (If you want warnings about annotations without this `__future__` import, you can write your own linter.)

**Comment by ambv** [comment]
Alright, makes sense.

**Comment by ambv** [comment]
This is not the place to discuss this but FTR I hope we won't make Python 4.0 another bag of pending incompatibilities.

**Comment by gvanrossum** [comment]
The main incompatibility will probably be Larry's Gilectomy, which may break every 3rd party package. Everything else will pale in comparison.

**Comment by ambv** [comment]
Solved by https://github.com/ambv/static-annotations/commit/5067c94d3a75ed17497d7386995b2861dd90cb1d. Leaving open pending disccusion.
