### ISSUE TITLE
Be honest about non-typing use cases

### ISSUE THREAD

**Issue by gvanrossum** [ambv/static-annotations#5]
While the PEP states

> Annotations are still available for arbitrary use besides type checking.
> Using ``@typing.no_type_hints`` in this case is recommended to
> disambiguate the use case.

it breaks backwards compatibility for those use cases (since presumably pretty much all non-typing use cases will be using run-time introspection) and the intent of the PEP (reading between the lines) is clearly to move closer towards the "annotations are for typing only" position. Not that I'm disagreeing with that, I just want it to be clear that that's the primary perspective from which decisions around annotation syntax and semantics will be made in the future.

**Comment by ambv** [comment]
Fair enough to say "and by the way, in Python 4 non-typing usage of annotations is not supported."

However, this makes the opposition to PEP 563 a bigger issue. I chose careful language and decided to postpone this discussion to give this PEP a better chance of getting accepted.

If you think I shouldn't worry about this, I'm happy to make this PEP state the end goal openly.

**Comment by gvanrossum** [comment]
We may get opposition on this basis *anyway*. So better be prepared.

**Comment by ambv** [comment]
I tried to word this "and by the way" nicely in the PEP as is but that really changes what the PEP is about. It almost makes the postponed evaluation an implementation detail of the over-arching "we are disallowing non-typing use of annotations". We'd need a new PEP title, discuss the deprecation timeline, etc. This really sounds like its own PEP.

I agree it would be deceptive to claim "hey we're just doing this one thing with annotations but other uses are perfectly fine" in PEP 563 and then slam another PEP a few months later saying "no, actually it's typing or the highway".

Which sounds like the "non-typing annotation use deprecation" PEP should be written separately... and accepted first.

**Comment by gvanrossum** [comment]
That PEP isn't going to be acceptable to the community until Python 4.0.

**Comment by ambv** [comment]
This is going to be fun. Fixed by e51f52b86bdb3cb46634099c9ada0948769d5f95, please approve this language.
