### ISSUE TITLE
Introspection may blow up in some cases

### ISSUE THREAD

**Issue by gvanrossum** [ambv/static-annotations#7]
This isn't new but still surprising:

- in a.py: `class C: …`
- in another file
  `if TYPE_CHECKING: from a import C`
  `def foo(x: C): …`
- introspection won’t know what `C` refers to (but this should work from mypy's POV).

**Comment by ambv** [comment]
This is already documented in "Runtime annotation resolution and ``TYPE_CHECKING``".

**Comment by gvanrossum** [comment]
Great. Glad to see that here you're using "will fail" rather than "is invalid". :-)
