### ISSUE TITLE
Validation of expressions in annotations

### ISSUE THREAD

**Issue by ambv** [ambv/static-annotations#8]
The implementation needs to address this, raising syntax and name errors appropriately.

Complications:
- the compiler doesn't keep a symbol table around
- nested classes (local scope) complicate the execution context

Essentially, it looks like I will have to grow a C implementation of `get_type_hints()` that works after compilation.  Ideally this would become the only implementation in Python 4.

**Comment by gvanrossum** [comment]
Whoa. Checking for name errors on annotations at compile time should be out of scope. Don't go there. It would become 10x more complex and you'd have an infinity of new edge cases. (Syntax errors are obviously in scope.)

**Comment by ambv** [comment]
Mentioned syntax errors (and explicitly listed name errors as out of scope) in 1785d621de6d4167a64762ed9ef9b479d718ffd2.

**Comment by gvanrossum** [comment]
Feel free to close this issue. :-)
